// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: fundkit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioRequest) Reset() {
	*x = PortfolioRequest{}
	mi := &file_fundkit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioRequest) ProtoMessage() {}

func (x *PortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fundkit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioRequest.ProtoReflect.Descriptor instead.
func (*PortfolioRequest) Descriptor() ([]byte, []int) {
	return file_fundkit_proto_rawDescGZIP(), []int{0}
}

func (x *PortfolioRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalValue    float64                `protobuf:"fixed64,2,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	Holdings      []*MutualFundHolding   `protobuf:"bytes,3,rep,name=holdings,proto3" json:"holdings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioResponse) Reset() {
	*x = PortfolioResponse{}
	mi := &file_fundkit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioResponse) ProtoMessage() {}

func (x *PortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fundkit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioResponse.ProtoReflect.Descriptor instead.
func (*PortfolioResponse) Descriptor() ([]byte, []int) {
	return file_fundkit_proto_rawDescGZIP(), []int{1}
}

func (x *PortfolioResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PortfolioResponse) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *PortfolioResponse) GetHoldings() []*MutualFundHolding {
	if x != nil {
		return x.Holdings
	}
	return nil
}

type MutualFundHolding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FundName      string                 `protobuf:"bytes,1,opt,name=fund_name,json=fundName,proto3" json:"fund_name,omitempty"`
	Units         float64                `protobuf:"fixed64,2,opt,name=units,proto3" json:"units,omitempty"`
	Nav           float64                `protobuf:"fixed64,3,opt,name=nav,proto3" json:"nav,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutualFundHolding) Reset() {
	*x = MutualFundHolding{}
	mi := &file_fundkit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutualFundHolding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutualFundHolding) ProtoMessage() {}

func (x *MutualFundHolding) ProtoReflect() protoreflect.Message {
	mi := &file_fundkit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutualFundHolding.ProtoReflect.Descriptor instead.
func (*MutualFundHolding) Descriptor() ([]byte, []int) {
	return file_fundkit_proto_rawDescGZIP(), []int{2}
}

func (x *MutualFundHolding) GetFundName() string {
	if x != nil {
		return x.FundName
	}
	return ""
}

func (x *MutualFundHolding) GetUnits() float64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *MutualFundHolding) GetNav() float64 {
	if x != nil {
		return x.Nav
	}
	return 0
}

type PnLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PnLRequest) Reset() {
	*x = PnLRequest{}
	mi := &file_fundkit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PnLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PnLRequest) ProtoMessage() {}

func (x *PnLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fundkit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PnLRequest.ProtoReflect.Descriptor instead.
func (*PnLRequest) Descriptor() ([]byte, []int) {
	return file_fundkit_proto_rawDescGZIP(), []int{3}
}

func (x *PnLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PnLResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalValue          float64                `protobuf:"fixed64,2,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	TotalUnrealizedGain float64                `protobuf:"fixed64,3,opt,name=total_unrealized_gain,json=totalUnrealizedGain,proto3" json:"total_unrealized_gain,omitempty"`
	Holdings            []*HoldingPnL          `protobuf:"bytes,4,rep,name=holdings,proto3" json:"holdings,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PnLResponse) Reset() {
	*x = PnLResponse{}
	mi := &file_fundkit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PnLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PnLResponse) ProtoMessage() {}

func (x *PnLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fundkit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PnLResponse.ProtoReflect.Descriptor instead.
func (*PnLResponse) Descriptor() ([]byte, []int) {
	return file_fundkit_proto_rawDescGZIP(), []int{4}
}

func (x *PnLResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PnLResponse) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *PnLResponse) GetTotalUnrealizedGain() float64 {
	if x != nil {
		return x.TotalUnrealizedGain
	}
	return 0
}

func (x *PnLResponse) GetHoldings() []*HoldingPnL {
	if x != nil {
		return x.Holdings
	}
	return nil
}

type HoldingPnL struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FundId         string                 `protobuf:"bytes,1,opt,name=fund_id,json=fundId,proto3" json:"fund_id,omitempty"`
	FundName       string                 `protobuf:"bytes,2,opt,name=fund_name,json=fundName,proto3" json:"fund_name,omitempty"`
	Units          float64                `protobuf:"fixed64,3,opt,name=units,proto3" json:"units,omitempty"`
	InvestedAmount float64                `protobuf:"fixed64,4,opt,name=invested_amount,json=investedAmount,proto3" json:"invested_amount,omitempty"`
	Nav            float64                `protobuf:"fixed64,5,opt,name=nav,proto3" json:"nav,omitempty"`
	CurrentValue   float64                `protobuf:"fixed64,6,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	UnrealizedGain float64                `protobuf:"fixed64,7,opt,name=unrealized_gain,json=unrealizedGain,proto3" json:"unrealized_gain,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HoldingPnL) Reset() {
	*x = HoldingPnL{}
	mi := &file_fundkit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingPnL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingPnL) ProtoMessage() {}

func (x *HoldingPnL) ProtoReflect() protoreflect.Message {
	mi := &file_fundkit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingPnL.ProtoReflect.Descriptor instead.
func (*HoldingPnL) Descriptor() ([]byte, []int) {
	return file_fundkit_proto_rawDescGZIP(), []int{5}
}

func (x *HoldingPnL) GetFundId() string {
	if x != nil {
		return x.FundId
	}
	return ""
}

func (x *HoldingPnL) GetFundName() string {
	if x != nil {
		return x.FundName
	}
	return ""
}

func (x *HoldingPnL) GetUnits() float64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *HoldingPnL) GetInvestedAmount() float64 {
	if x != nil {
		return x.InvestedAmount
	}
	return 0
}

func (x *HoldingPnL) GetNav() float64 {
	if x != nil {
		return x.Nav
	}
	return 0
}

func (x *HoldingPnL) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *HoldingPnL) GetUnrealizedGain() float64 {
	if x != nil {
		return x.UnrealizedGain
	}
	return 0
}

var File_fundkit_proto protoreflect.FileDescriptor

const file_fundkit_proto_rawDesc = "" +
	"\n" +
	"\rfundkit.proto\x12\afundkit\"+\n" +
	"\x10PortfolioRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x85\x01\n" +
	"\x11PortfolioResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtotal_value\x18\x02 \x01(\x01R\n" +
	"totalValue\x126\n" +
	"\bholdings\x18\x03 \x03(\v2\x1a.fundkit.MutualFundHoldingR\bholdings\"X\n" +
	"\x11MutualFundHolding\x12\x1b\n" +
	"\tfund_name\x18\x01 \x01(\tR\bfundName\x12\x14\n" +
	"\x05units\x18\x02 \x01(\x01R\x05units\x12\x10\n" +
	"\x03nav\x18\x03 \x01(\x01R\x03nav\"%\n" +
	"\n" +
	"PnLRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xac\x01\n" +
	"\vPnLResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtotal_value\x18\x02 \x01(\x01R\n" +
	"totalValue\x122\n" +
	"\x15total_unrealized_gain\x18\x03 \x01(\x01R\x13totalUnrealizedGain\x12/\n" +
	"\bholdings\x18\x04 \x03(\v2\x13.fundkit.HoldingPnLR\bholdings\"\xe1\x01\n" +
	"\n" +
	"HoldingPnL\x12\x17\n" +
	"\afund_id\x18\x01 \x01(\tR\x06fundId\x12\x1b\n" +
	"\tfund_name\x18\x02 \x01(\tR\bfundName\x12\x14\n" +
	"\x05units\x18\x03 \x01(\x01R\x05units\x12'\n" +
	"\x0finvested_amount\x18\x04 \x01(\x01R\x0einvestedAmount\x12\x10\n" +
	"\x03nav\x18\x05 \x01(\x01R\x03nav\x12#\n" +
	"\rcurrent_value\x18\x06 \x01(\x01R\fcurrentValue\x12'\n" +
	"\x0funrealized_gain\x18\a \x01(\x01R\x0eunrealizedGain2\x92\x01\n" +
	"\x10PortfolioService\x12E\n" +
	"\fGetPortfolio\x12\x19.fundkit.PortfolioRequest\x1a\x1a.fundkit.PortfolioResponse\x127\n" +
	"\n" +
	"GetUserPnL\x12\x13.fundkit.PnLRequest\x1a\x14.fundkit.PnLResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_fundkit_proto_rawDescOnce sync.Once
	file_fundkit_proto_rawDescData []byte
)

func file_fundkit_proto_rawDescGZIP() []byte {
	file_fundkit_proto_rawDescOnce.Do(func() {
		file_fundkit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fundkit_proto_rawDesc), len(file_fundkit_proto_rawDesc)))
	})
	return file_fundkit_proto_rawDescData
}

var file_fundkit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fundkit_proto_goTypes = []any{
	(*PortfolioRequest)(nil),  // 0: fundkit.PortfolioRequest
	(*PortfolioResponse)(nil), // 1: fundkit.PortfolioResponse
	(*MutualFundHolding)(nil), // 2: fundkit.MutualFundHolding
	(*PnLRequest)(nil),        // 3: fundkit.PnLRequest
	(*PnLResponse)(nil),       // 4: fundkit.PnLResponse
	(*HoldingPnL)(nil),        // 5: fundkit.HoldingPnL
}
var file_fundkit_proto_depIdxs = []int32{
	2, // 0: fundkit.PortfolioResponse.holdings:type_name -> fundkit.MutualFundHolding
	5, // 1: fundkit.PnLResponse.holdings:type_name -> fundkit.HoldingPnL
	0, // 2: fundkit.PortfolioService.GetPortfolio:input_type -> fundkit.PortfolioRequest
	3, // 3: fundkit.PortfolioService.GetUserPnL:input_type -> fundkit.PnLRequest
	1, // 4: fundkit.PortfolioService.GetPortfolio:output_type -> fundkit.PortfolioResponse
	4, // 5: fundkit.PortfolioService.GetUserPnL:output_type -> fundkit.PnLResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fundkit_proto_init() }
func file_fundkit_proto_init() {
	if File_fundkit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fundkit_proto_rawDesc), len(file_fundkit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fundkit_proto_goTypes,
		DependencyIndexes: file_fundkit_proto_depIdxs,
		MessageInfos:      file_fundkit_proto_msgTypes,
	}.Build()
	File_fundkit_proto = out.File
	file_fundkit_proto_goTypes = nil
	file_fundkit_proto_depIdxs = nil
}
